- 👋 Hi, I’m MR SIFISO S
- 👀 I’m interested in ... PUBLIC AND PRIVATE BIZ
- 🌱 I’m currently learning ...CYBERCRIME ANALYSIS
- 💞️ I’m looking to collaborate on ... CLOUD/NETWORKING SECURITY/DNS MAMANGEMENT AND MANY MORE
- 📫 How to reach me ...mail: dnsadmin1@duck.com or dcb.association.wcp@gmail.com
- 😄 Pronouns: ...
- ⚡ Fun fact: ...https://www.google.com/search?q=sourceid=chrome&ie=UTF-8

<!--- BEGIN PGP PRIVATE KEY BLOCK---!> HTTP://OCTOPUS.COM 
MozillaThu9496/MozillaThu9496 is a ✨ special ✨ repository because its `PGP ARE A PUBLIC KEY` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
---> https://www.powerdns.com
